[package]
name = "bite_sized_earth"
version = "0.1.0"
authors = ["Zhuang Jiawei <zjw@stu.scau.edu.cn>"]
edition = "2024"


[workspace]
resolver = "3"
members = ["crates/bse_sim", "crates/bse_shell"]

[workspace.dependencies]
bevy = { version = "0.18" }
bse_sim = { path = "crates/bse_sim" }
bse_shell = { path = "crates/bse_shell" }

[features]
dev = ["bse_shell/dev"]

[dependencies]
bevy = { workspace = true }
bse_sim = { workspace = true }
bse_shell = { workspace = true }
