use bevy::prelude::*;
use smallvec::SmallVec;

use crate::world::GridLayer;

#[cfg(feature = "dev")]
#[derive(Message, Debug)]
pub struct DebugSpawnStaffRequest {
  pub grid_x: i32,
  pub grid_y: i32,
}

#[cfg(feature = "dev")]
#[derive(Message, Debug)]
pub struct DebugSpawnCustomerRequest {
  pub grid_x: i32,
  pub grid_y: i32,
}

/// Broadcast whenever a floor / ceiling / surface placement or removal occurs.
/// Multiple systems (interaction refresh, shell effects, etc.) read independently.
#[derive(Message, Debug)]
pub struct GridChangedMessage {
  pub cells: SmallVec<[(i32, i32); 8]>,
  pub layer: GridLayer,
}

// Re-export message types generated by the macro in construction.rs
pub use crate::construction::{
  RequestDemolishAppliance, RequestPlaceChair, RequestPlaceRegister, RequestPlaceStove,
  RequestPlaceTable,
};

pub fn register_all(app: &mut App) {
  #[cfg(feature = "dev")]
  {
    app.add_message::<DebugSpawnStaffRequest>();
    app.add_message::<DebugSpawnCustomerRequest>();
  }
  app.add_message::<RequestPlaceTable>();
  app.add_message::<RequestPlaceChair>();
  app.add_message::<RequestPlaceRegister>();
  app.add_message::<RequestDemolishAppliance>();
  app.add_message::<RequestPlaceStove>();
  app.add_message::<GridChangedMessage>();
}
