use bevy::prelude::*;

#[cfg(feature = "dev")]
#[derive(Message, Debug)]
pub struct DebugSpawnStaffRequest {
  pub grid_x: i32,
  pub grid_z: i32,
}

#[cfg(feature = "dev")]
#[derive(Message, Debug)]
pub struct DebugSpawnCustomerRequest {
  pub grid_x: i32,
  pub grid_z: i32,
}

// ===== 消息类型由 construction.rs 中的 define_appliances! 宏生成 =====

// Re-export message types generated by the macro in construction.rs
pub use crate::construction::{
    RequestPlaceTable,
    RequestPlaceChair,
    RequestPlaceRegister,
    RequestPlaceStove,
    RequestDemolishAppliance,
};

pub fn register_all(app: &mut App) {
  #[cfg(feature = "dev")]
  {
    app.add_message::<DebugSpawnStaffRequest>();
    app.add_message::<DebugSpawnCustomerRequest>();
  }
  app.add_message::<RequestPlaceTable>();
  app.add_message::<RequestPlaceChair>();
  app.add_message::<RequestPlaceRegister>();
  app.add_message::<RequestDemolishAppliance>();
  app.add_message::<RequestPlaceStove>();
}
